### ISSUE TITLE
Edge Permission denied

### ISSUE THREAD

**Issue by hooverweb** [ckeditor/ckeditor-dev#2035]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using Microsoft Edge, go to: https://ckeditor.com/latest/samples/index.html
2. Click any of the following buttons: Image, Spell Check, Style, Format, Size (and many others)
3. You will receive a Javascript Error: Permission denied

When running the samples on my website, there are no details for the error message (I'm not familiar with Edge though). But on the ckeditor.com samples page, there is a message that shows some more details. Here's the details after clicking the image button and receiving the permission denied error:

Could not locate https://ckeditor.com/latest/node_modules/cksource-samples-framework/components/grid/grid.less specified in source map

* Browser: Edge (Microsoft Edge 42.17134.1.0)
* OS: Window 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Standard

**Comment by jacekbogdanski** [comment]
Hello,

I don't have any permission problems using your version of Edge. I think it's more like browser configuration than CKEditor issue or Edge upstream. However, we have in our GH history similar issue: https://github.com/ckeditor/ckeditor-dev/issues/1503 so it looks like this issue affects more users.

Could you give us more information about the issue? Like full error stack from a console?

**Comment by hooverweb** [comment]
Strange. I pulled up Edge again to get the information needed and I didn't get the error (all the buttons were working), then I refreshed and tried clicking the image button and it threw the error.

A client actually brought this to my attention when she couldn't get the editor to work on her Windows 10/Ege system.

I'm not familiar with Edge (or Javascript, all that much) so let me know if you need something else other than the below.

Here's what I get when right clicking -> copy all in the "Call stack" box:

[Main Thread]
Anonymous function [Line: 1, Col: 2], index.html
Global code [Line: 1, Col: 2], index.html
append [Line: 89, Col: 293], ckeditor.js
appendTo [Line: 65, Col: 417], ckeditor.js
CKEDITOR.dialog.prototype.show [Line: 565, Col: 296], ckeditor.js
openDialog [Line: 604, Col: 178], ckeditor.js
Anonymous function [Line: 604, Col: 492], ckeditor.js
f [Line: 235, Col: 358], ckeditor.js
n [Line: 235, Col: 448], ckeditor.js
p [Line: 236, Col: 81], ckeditor.js
Anonymous function [Line: 236, Col: 509], ckeditor.js
[Async Call]
e.$.onload [Line: 236, Col: 487], ckeditor.js

![capture](https://user-images.githubusercontent.com/2574722/40742981-d5ed20d6-6415-11e8-870c-1561f0f36d0f.PNG)

**Comment by hkakumanu-ttc** [comment]
I am facing the same issue as well in the browser 42.17134.1.0

**Comment by jacekbogdanski** [comment]
Thanks for your replies. After some testing, I was able to reproduce the issue. However, I didn't see any invalid behavior when using CKEditor after the error. Could you confirm if there is any functional CKEditor issue except console error message?

**Comment by hooverweb** [comment]
I thought the error was making the editor buttons unresponsive, at the time I submitted the report. But I tried it again just now and the buttons continued to work. So it seems to still be functional.

**Comment by hkakumanu-ttc** [comment]
@jacekbogdanski My editor freezes and will not work. I think its just not the console error message.

**Comment by shubhamkumar11** [comment]
Please see the attached HTML file. I am using ie version 11.0.96
When I load the HTML the debugger relieve shows script 70 Permission Denied for a simple javascript console.log.
Any ideas respected.

**Comment by jswiderski** [comment]
I have checked:
Microsoft EdgeHTML 17.17134
Microsoft Edge 42.17134.1.0
and the error indeed gets thrown but besides the error in console, editor works without problems.

It seems error gets thrown whenever dialog or dropdown using iframe is opened: images, flash, link, mathjax, image button, color buttons, format dropdown, font dropdown, font-size dropdown, styles dropdown and scayt.

**Comment by jswiderski** [comment]
**NOTE:** @hkakumanu-ttc has provided a fiddle in which editor was freezing. It has turned out user was using version 4.5.1 while support for MS Edge has been first introduced in CKEditor 4.5.2. After upgrading to 4.5.2 or above error was throw but editor worked as expected.

**Comment by shubhamkumar11** [comment]
Edge Permission denied #2035
help your last my reply on post.

**Comment by jswiderski** [comment]
Perhaps this comment will be of any use: https://stackoverflow.com/questions/5352057/script70-permission-denied-ie9

**Comment by mlewand** [comment]
It happens for anything reusing `floatpanel`  component. I don't recall this issue being present earlier. It would be great if we could test it with earlier Edge version, as I smell browser regression here.

**Comment by engineering-this** [comment]
https://github.com/ckeditor/ckeditor-dev/blob/12b7a8600fb7ca8e18fc6f48938337b118c0e416/plugins/panel/plugin.js#L172

When iframe contains any js code within `src` attribute Edge throws 'Permission denied'.

**Comment by mlewand** [comment]
Fixed with #2391 and will be released in 4.10.2 and can be already checked in early preview: https://ckeditor4-preview.ckeditor.com/master/samples/index.html

**Comment by vicnoob** [comment]
@mlewand 
I still get permission denied error in both IE11 and Edge. Im using CKeditor 4.11.1
The error in on line:

{return new CKEDITOR.dom.document(this.$.ownerDocument||this.$.parentNode.ownerDocument)}

**Comment by mlewand** [comment]
@vicnoob I'm sure it is no longer reproducible, and I can confirm it is fixed.

Maybe you're simply dealing with a different scenario (reproduce steps) in which case this should be a different issue. You can check latest CKEditor release here: https://ckeditor.com/latest/samples/index.html
